print (" The file was created using RStudio ")
print (" And it lives on Git ")
print (" And this is the second change ")
print (" The fourth line has been added to test for pull ")
print (" Adding the fifth line ")
print (" Sixth change ")